spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:packer.db
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
server:
  port: 5252
packer-property:
  installList: UserPackages.json
  licenseKey: licenseKey
  engineer-auth-serverIP: http://localhost:9292
