spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:packer.db

installListFilePath: C:\\Users\\sinny\\Desktop\\develop\\springBoot\\packer\\UserPackages.json

mybatis:
  mapper-locations: classpath*:mybatis\\mapper\\*.xml
server:
  port: 5252
